version: "3"
services:
    db:
        container_name: db
        image: mysql:8
        restart: always
        command: --default-authentication-plugin=mysql_native_password
        ports:
            - "13306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db/sql-data:/var/lib/mysql
            - ./db/sql.d:/docker-entrypoint-initdb.d

    server:
        build: ./server
        depends_on:
            - db
        restart: always
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}?autoReconnect=true&useSSL=false
            SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
            SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - "8080:8080"

volumes:
    sql_data: {}